---
- hosts: all
  roles:
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Copy Running Config to TFTP server as Golden Config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://{{ var_tftp }}/golden_config.cli'
        config_type: 'cli'
        vrf: 'default'
